# Generated by Django 5.1.7 on 2025-04-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('accommodation_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('rented', 'Rented')], default='available', max_length=20)),
                ('distance', models.FloatField()),
                ('type', models.CharField(max_length=50)),
                ('period_of_availability', models.CharField(max_length=100)),
                ('number_of_beds', models.PositiveIntegerField()),
                ('number_of_bedrooms', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('period_of_availability', models.CharField(max_length=100)),
                ('number_of_beds', models.PositiveIntegerField()),
                ('number_of_bedrooms', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
