# Generated by Django 5.1.7 on 2025-04-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEDARSSpecialist',
            fields=[
                ('specialist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('signed_date', models.DateTimeField(auto_now_add=True)),
                ('contract_status', models.CharField(choices=[('signed', 'Signed'), ('failed', 'Failed')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HKUMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=10)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='status',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='number_of_bedrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='number_of_beds',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_accommodations', to='orders.cedarsspecialist'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='orders.propertyowner'),
        ),
        migrations.AddField(
            model_name='rating',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.accommodation'),
        ),
        migrations.AddField(
            model_name='rating',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.hkumember'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='orders.accommodation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='orders.hkumember'),
        ),
        migrations.AddField(
            model_name='contract',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='orders.reservation'),
        ),
    ]
