# Generated by Django 5.1.7 on 2025-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='specialist',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='member',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='member',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='accommodation',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='geo_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=10),
        ),
        migrations.DeleteModel(
            name='CEDARSSpecialist',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='HKUMember',
        ),
        migrations.DeleteModel(
            name='PropertyOwner',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
